### ISSUE TITLE
problème connexion à Rstudio via Onyxia

### ISSUE THREAD

**Issue by khaledlarbi** [InseeFrLab/sspcloud#1]
Bonjour,

Merci beaucoup pour la plateforme. J'ai un petit soucis : jusqu'à la semaine dernière, pas de problème pour me connecter à RStudio, il suffisait d'utiliser comme id **rstudio** et le mdp associé à mes services. 

Sauf que depuis hier, cela ne fonctionne plus et lorsque je vais dans l'onglet `README` du service RStudio, j'ai la fenêtre suivante : 
![image](https://user-images.githubusercontent.com/45902413/128678670-659a74a1-d5d2-4406-bf96-c40ee7d17cb2.png)

Est-ce que quelqu'un a déjà rencontré un problème similaire ?

Encore merci pour la plateforme !

**Comment by olevitt** [comment]
Bonjour,

Je me suis permis de transférer l'issue sur le projet sspcloud qui traite des problèmes liés spécifiquement à la plateforme sspcloud (le projet onyxia-web traite du projet opensource onyxia, indépendamment de la plateforme concernée).

Tu as quoi comme erreur ? 403 ? Authentification refusée ?

**Comment by garronej** [comment]
> Bonjour,
> 
> Merci beaucoup pour la plateforme. J'ai un petit soucis : jusqu'à la semaine dernière, pas de problème pour me connecter à RStudio, il suffisait d'utiliser comme id **rstudio** et le mdp associé à mes services.
> 
> Sauf que depuis hier, cela ne fonctionne plus et lorsque je vais dans l'onglet `README` du service RStudio, j'ai la fenêtre suivante :
> ![image](https://user-images.githubusercontent.com/45902413/128678670-659a74a1-d5d2-4406-bf96-c40ee7d17cb2.png)
> 
> Est-ce que quelqu'un a déjà rencontré un problème similaire ?
> 
> Encore merci pour la plateforme !

Salut!
Sur la capture il y à `****` tu l'a édité à la main depuis avec le devlopper tool ou c'est vraiment ça que tu as?

**Comment by khaledlarbi** [comment]
> Bonjour,
> 
> Je me suis permis de transférer l'issue sur le projet sspcloud qui traite des problèmes liés spécifiquement à la plateforme sspcloud (le projet onyxia-web traite du projet opensource onyxia, indépendamment de la plateforme concernée).
> 
> Tu as quoi comme erreur ? 403 ? Authentification refusée ?

Merci pour vos réponses rapides ! J'ai une authentification refusée à cause du mot de passe qui ne semble pas être bon (alors que j'ai bien vérifie qu'il s'agissait bien du mdp de mes services).



> > Bonjour,
> > Merci beaucoup pour la plateforme. J'ai un petit soucis : jusqu'à la semaine dernière, pas de problème pour me connecter à RStudio, il suffisait d'utiliser comme id **rstudio** et le mdp associé à mes services.
> > Sauf que depuis hier, cela ne fonctionne plus et lorsque je vais dans l'onglet `README` du service RStudio, j'ai la fenêtre suivante :
> > ![image](https://user-images.githubusercontent.com/45902413/128678670-659a74a1-d5d2-4406-bf96-c40ee7d17cb2.png)
> > Est-ce que quelqu'un a déjà rencontré un problème similaire ?
> > Encore merci pour la plateforme !
> 
> Salut!
> Sur la capture il y à `****` tu l'a édité à la main depuis avec le devlopper tool ou c'est vraiment ça que tu as?

Non, je n'ai rien édité à la main. C'est apparu hier alors que je voulais lancer une session de R Studio.

**Comment by olevitt** [comment]
De ce que je vois dans la configuration de ton service, le mot de passe est vide. As tu essayé de le changer quand tu as configuré ton rstudio au moment de sa création ? 

Est ce que tu nous donne la permission d'impersonater ton identité (se connecter sur onyxia avec ton compte) afin qu'on regarde un peu plus en détail ce qui a pu se passer ? Si oui, j'en profiterai pour remettre ton mot de passe onyxia comme mot de passe du service. Sinon, je peux mettre un autre mot de passe sur ce service et te l'envoyer par email.

**Comment by khaledlarbi** [comment]
Je l'ai changé ce matin en demandant la génération d'un nouveau mot de passe automatique (je crois qu'il y a une icone pour ça)

Aucun problème pour _impersonater_ mon idenité !

Bon courage !

**Comment by olevitt** [comment]
Ca te pose pas de problèmes si je redémarre ton service ? Tu as du code ou des données non sauvegardées que tu veux récupérer dessus avant ?

**Comment by khaledlarbi** [comment]
Non aucun problème !

**Comment by olevitt** [comment]
J'ai changé le mot de passe pour remettre celui de ton compte onyxia, tu peux me confirmer que c'est bon pour toi ?
Par contre je sais pas exactement ce qui s'est passé. Normalement le bouton de changement de mot de passe te génère un nouveau mot de passe mais ne change pas le mot de passe des services déjà déployés

**Comment by khaledlarbi** [comment]
Je viens de tester : je peux me connecter au service ! Merci beaucoup 👍🏽

**Comment by olevitt** [comment]
👍

**Comment by khaledlarbi** [comment]
Bonsoir, 

Je tiens à m'excuser s'il fallait ouvrir un nouvel *issue* mais j'ai rencontré exactement le même problème en créant un nouveau service. Je n'ai pas changé la manière de créer un service par rapport à la semaine dernière. 

Est-ce que vous savez si ce problème est inhérent à mon compte ?

Bonne soirée,

Khaled

**Comment by olevitt** [comment]
Pas de problèmes, j'ai réouvert l'issue.
@fcomte tu peux regarder quand t'as un moment ? On dirait que l'injection de son MDP vault se fait pas bien

**Comment by garronej** [comment]
> Pas de problèmes, j'ai réouvert l'issue.
> @fcomte tu peux regarder quand t'as un moment ? On dirait que l'injection de son MDP vault se fait pas bien

C'est pas plutôt ma faute ça?

**Comment by olevitt** [comment]
Fort possible oui, tu peux regarder aussi :)

**Comment by khaledlarbi** [comment]
Bonjour,

J'ai relancé un RStudio en utilisant une configuration que j'avais enregistrée mais malheureusement, je suis à nouveau confronté au même soucis (mdp sous la forme ****) et impossibilité de me connecter ...

Est-ce que vous sauriez d'où provient le problème ?

Très bonne journée,

Khaled

**Comment by garronej** [comment]
Pourriez vous, s'il vous plait, coller l'URL du service enregistrer en question ici?

**Comment by khaledlarbi** [comment]
C'est de ce lien que tu parles : https://klarbi-rstudio-6643022849268276647-rstudio-ihm.kub.sspcloud.fr/auth-sign-in?appUri=%2F ?

**Comment by garronej** [comment]
Non, plutôt celui là:
![image](https://user-images.githubusercontent.com/6702424/131672666-f182ac2c-4a08-4643-af44-0a1ac1b9eb96.png)

**Comment by khaledlarbi** [comment]
Oupsi : voici le bon lien https://klarbi-rstudio-6643022849268276647-rstudio-ihm.kub.sspcloud.fr/auth-sign-in?appUri=%2F

**Comment by garronej** [comment]
Je crois que vous avez par erreur copier le même liens.  
A moins que ça soit mon code qui bug...  
Voilà ce dont j'ai besoin:  


https://user-images.githubusercontent.com/6702424/131677521-1726fc0a-ba6a-4cae-a4c7-63a779181632.mov

**Comment by khaledlarbi** [comment]
Lorsque je le fais, je n'ai pas le bouton "Modifier"
![image](https://user-images.githubusercontent.com/45902413/131678598-0686e636-29a5-4f39-a7f5-27cf741412b3.png)

**Comment by garronej** [comment]
Ah vous pardon! Vous n'êtes pas sur l'instance publique! Et donc quand vous faites copier 'URL ça donne un liens en ` https://klarbi-rstudio-6643022849268276647....` ?

**Comment by khaledlarbi** [comment]
Exactement, ça me donne ce lien là quand je fais "copier URL" : 
https://klarbi-rstudio-6643022849268276647-rstudio-ihm.kub.sspcloud.fr/auth-sign-in?appUri=%2F

**Comment by garronej** [comment]
Ok, I see, it's an old version of onyxia-web.  
Can you try this then:  
![image](https://user-images.githubusercontent.com/6702424/131749918-324e2f66-8d3f-4da6-a033-94471f06b379.png)

**Comment by khaledlarbi** [comment]
Voici le lien que j'obtiens en faisant ce que tu as indiqué plus haut : 
https://onyxia-preview.lab.sspcloud.fr/launcher/inseefrlab-helm-charts-datascience/rstudio?git.enabled=false&resources.limits.cpu=%C2%AB50000m%C2%BB
