### ISSUE TITLE
How to cite SSP Cloud?

### ISSUE THREAD

**Issue by fBedecarrats** [InseeFrLab/sspcloud#15]
Is there a bibliographical citation to refer to if I want to mention SSP Cloud and/or onyxia in some academic training materials? R or Python package developers often insist on their materials to be properly cited. Do you have such expectation from your users?

**Comment by garronej** [comment]
Hello,  
Thank you for your question,  

If you want to cite Onyxia as an open source project its: https://onyxia.sh  
If you want to cite the SSP Cloud as an offer of service or as a community: https://sspcloud.fr  
If you want to cite a particular course or training, you can provide the full link like https://www.sspcloud.fr/formation?search=&path=%5B%22Initiation%20%C3%A0%20Python%22%5D  

@RLesur could you confirm we are on the same page on this?

**Comment by RLesur** [comment]
Here is a Zotero RDF entry:

```xml
<rdf:RDF
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
 xmlns:z="http://www.zotero.org/namespaces/export#"
 xmlns:dc="http://purl.org/dc/elements/1.1/"
 xmlns:foaf="http://xmlns.com/foaf/0.1/"
 xmlns:dcterms="http://purl.org/dc/terms/"
 xmlns:bib="http://purl.org/net/biblio#">
    <bib:Data rdf:about="https://onyxia.sh">
        <z:itemType>computerProgram</z:itemType>
        <dc:publisher>
           <foaf:Organization><foaf:name>INSEE</foaf:name></foaf:Organization>
        </dc:publisher>
        <dc:title>Onyxia</dc:title>
        <dc:date>2022</dc:date>
        <dc:identifier>
           <dcterms:URI><rdf:value>https://onyxia.sh</rdf:value></dcterms:URI>
        </dc:identifier>
    </bib:Data>
</rdf:RDF>
```

and a BibTeX one:

```tex
@misc{onyxia,
	title = {Onyxia},
	url = {https://onyxia.sh},
	publisher = {INSEE},
	year = {2022},
}
```
