### ISSUE TITLE
tokens updated each time the page is refreshed 

### ISSUE THREAD

**Issue by linai55a** [InseeFrLab/sspcloud#19]
Hi everyone, 

We have noticed that each time the website https://datalab.sspcloud.fr/ is reloaded, new tokens for Vault, MinIo storage and Kubernetes are generated. This may cause some prejudice in CI/CD deployment or in storage access. Is this behaviour expected and can it be easily adressed ? 

Many thanks, 

Lina

**Comment by fcomte** [comment]
Je pense qu'on peut le faire en francais ici : je comprends pas trop car Onyxia ne revoke aucun token. Je comprends pas trop pourquoi des choses casses du coup

**Comment by garronej** [comment]
@linai55a C'est en effet le cas, pourrais tu nous donner un peut plus de détails qui nous aiderais a comprendre dans quelle cas ce comportement pourrais se réveller problématique?  
Dans tout les cas sachez que vous pouvez fixer les tokens via l'enregistrement de configurations ou les config S3.  

@fcomte Ca me fait penser que ça pourrais potentiellement être interessant de storer les tokens S3 dans vault histoire de ne pas spammer STS... On a déjà un mechanisme qui fait en sorte que si on request un token et qu'on en a un en cache mais que sa durée de vie restante est moins de 90% de sa durée de vie total alors on request un nouveau token. Du coup ça serais pas très dur a metre en place.  
Pour le token Vault par contre évidement ça ne marche pas. On peut utiliser le local storage du navigateur mais je crois qu'il vaudrais mieux éviter niveau sécu.  
Enfin je sais pas c'est juste une idée comme ça, si ça se trouve faire une requette vault c'est aussi cher qu'un requette STS.

**Comment by garronej** [comment]
@linai55a I did a Tango to show you:  

https://app.tango.us/app/embed/9463fc74-4217-4b70-aaee-b91b054fe2ed

**Comment by linai55a** [comment]
Bonjour @fcomte et @garronej, merci pour vos retours. Ce comportement est problématique surtout dans Nubonyxia, pour lequel en raison de lenteur de réseau, l'utilisateur est souvent amené à rafraichir la page. En terme d'incidence, on pense que cela peut casser les déploiements CI/CD sur Gitlab ainsi que les services dépendant d'un accès à minio.

Merci @garronej pour Tango je ne connaissais pas cette astuce

**Comment by garronej** [comment]
@linai55a Ca y est c'est fait! Dans les dernière version d'Onyxia les token STS ne son plus obtenu a chaque rechargement de l'application Web. Ils sont persisté dans Vault et regénéré au besoin quand leur durée de vier réstante est inférieure a 90% de leur durée de vie total.  

Merci d'avoir ouver l'issue!

**Comment by fcomte** [comment]
In fact we will remove that cache. It's very hard to invalidate this cache and we have trouble with this fonctionnality.
