### ISSUE TITLE
Mettre en place les permissions aux Pages GitLab

### ISSUE THREAD

**Issue by statnmap** [InseeFrLab/sspcloud#2]
Les pages GitLab produites sur "pages.lab.sspcloud.fr" sont publiques, indépendemment du caractère privé ou public du projet.  
En fait, il semble que la gestion des permissions pour les Pages ne soit pas mise en place comme indiqué dans cette documentation: https://docs.gitlab.com/ee/administration/pages/index.html#access-control  

Notez qu'avec la version 14 pour GitLab dans un Docker, il y a actuellement un bug en cours de correction: https://github.com/sameersbn/docker-gitlab/issues/2375

**Comment by olevitt** [comment]
Hello, je me suis permis de transférer l'issue ici vu qu'elle concerne spécifiquement la plateforme sspcloud et non pas le projet opensource Onyxia.
Je vais regarder ce qu'on peut faire avec cette installation de gitlab. Pour information, ce gitlab a été installé via le chart helm https://docs.gitlab.com/charts/

**Comment by statnmap** [comment]
Désolé, je ne sais jamais sur quel Repo GitHub il faut poser sa question.  
On retrouve AccessControl dans la configuration globale Helm partagée ici: https://docs.gitlab.com/charts/charts/globals.html#configure-gitlab-pages

**Comment by olevitt** [comment]
Bien vu ! J'upgrade en activant ça d'ici quelques minutes, je te tiens au courant pour que tu puisses tester :)

**Comment by olevitt** [comment]
Bon, l'upgrade a mis en lumière un petit problème avec le stockage de fichiers sous-jacent :neutral_face: 
Du coup je pense que la mise à jour sera effective demain et pas aujourd'hui. Je te tiens au courant sur cette issue :)

**Comment by olevitt** [comment]
Bonjour,

Le problème a été résolu et la mise à jour est effective.
Normalement, l'access control de gitlab pages devrait être activé. Je te laisse tester ?

**Comment by statnmap** [comment]
Bonjour,
C'est effectivement réglé. Les Pages sont privées par défaut.  
Merci.
