### ISSUE TITLE
SSPCloud will be down from friday 14th 18:00 (Paris time) to monday morning

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/sspcloud#22]
### Important Notice: Scheduled Downtime for S3 Software Reinstallation

We would like to inform you about an upcoming scheduled downtime required for the reinstallation of our S3 software (MinIO). During this period, all S3 data will be transferred to another storage solution and then restored to a freshly installed MinIO environment.

**Please note the following important points:**

- **Data Preservation**: You will not lose any data during this process.
- **Service Accounts and Policies will be lost**: All service accounts and policies you may have created will be lost. You will need to recreate them after the reinstallation is complete.

Thank you for your understanding and cooperation.

**Comment by olevitt** [comment]
Hi ! 

Re-installation and re-copy went well. 
We plan to have SSPCloud fully back online by 09:00 today.
Users are advised to double check the content of their personal and project buckets.
You will also have to re-create any service account / bucket policy you previously had.
If you encounter any issue or need assistance please contact us either here or on Slack : https://join.slack.com/t/3innovation/shared_invite/zt-1hnzukjcn-6biCSmVy4qvyDGwbNI~sWg

**Comment by olevitt** [comment]
We are back online :partying_face: 
Welcome back

**Comment by olevitt** [comment]
Known issue : minio console (https://minio-console.lab.sspcloud.fr/) is currently broken (at least for SSO authentication).  
We are working on fixing it. If you need to create a service account while the console is down you can use https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-user-svcacct-add.html

**Comment by olevitt** [comment]
> Known issue : minio console (https://minio-console.lab.sspcloud.fr/) is currently broken (at least for SSO authentication). We are working on fixing it. If you need to create a service account while the console is down you can use https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-user-svcacct-add.html

Minio console troubleshooting is still in progress. 
Meanwhile if you need to create a service account, here is a procedure to do so :  
1. Create a service on the datalab in your personal project with S3 enabled  
2. Confirm `s3` connection is working with `mc ls s3/<your username>`
3. Prepare a `policy.json` file containing permissions for the bucket(s) you want to give access to the service account :  
```
{
    "Version": "2012-10-17",
    "Statement": [
     {
      "Effect": "Allow",
      "Action": [
       "s3:*"
      ],
      "Resource": [
       "arn:aws:s3:::projet-monprojet",
       "arn:aws:s3:::projet-monprojet/*"
      ]
     }
    ]
  }
```
4. Get the accesskey of your current user : `echo $AWS_ACCESS_KEY_ID`
5. Create the service account with the corresponding policy and the accesskey / secretkey you want :  
``` 
mc admin user svcacct add s3 $AWS_ACCESS_KEY_ID --access-key="WhateverAccesskeyYouWant" --secret-key="WhateverSecretkeyYouWant" --policy="policy.json"  
```  
(replace `WhateverSecretkeyYouWant` and `WhateverSecretkeyYouWant`)
6. Profit. You can now use `WhateverAccesskeyYouWant` and `WhateverSecretkeyYouWant` as credentials to access the specified bucket(s) :partying_face:
