### ISSUE TITLE
Personal namespaces will be wiped on December 25

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/sspcloud#23]
Hi ! :santa: 

We will be conducting a total cleanup of all services running in personal namespaces in SSPCloud on December 25 (exact time TBD).  
This includes every service you may have created (`vscode`, `jupyter`, `postgres` ... everything you installed through Onyxia UI) including their attached data (work, postgres data ...).  
This also includes everything you may have installed using the underlying Kubernetes cluster (advanced users) including the data (PVC).  

Data stored on S3 (my files) will NOT be affected by this cleanup.  
Vault (secrets, saved configurations ...) will NOT be affected by this cleanup.
SSPCloud's gitlab instance (https://git.lab.sspcloud.fr/) will NOT be affected by this cleanup.  
Projects spaces (`projet-`, only available if you belong to a group) will NOT be affected by this cleanup.  

You will be able to create services and deploy things again once the cleanup is done, just like before.

If for a specific reason you want your personal space to be excluded from this cleanup, please comment below, we will make sure to contact you.

Thank you for using SSPCloud

**Comment by garronej** [comment]
Worst chismas present of all time serious contender  

Back in the good old days we had a snowflakes theme for chrismass  

The devs really droped the ball on the latest seasons

**Comment by fcomte** [comment]
email has been sent to detail which ressources will be deleted.
You can saw them at any time with a terminal on vscode , jupyter or rstudio by writing 

```
kubectl get pods
kubectl get pvc
```

**Comment by olevitt** [comment]
Cleanup is scheduled for 20:00 CET today.  
It should not take long (let's say 1 hour to be safe).  
The datalab (Onyxia software) will be taken down during that time.
Please wait for a confirmation either here or in the Datalab's banner message that the cleanup operation is done before resuming normal operations after cleanup.  

Special note for `ENSAE` users : we temporarily exempted you from this cleanup as we know some of you are extensively using the platform for homework scheduled for later this week. If you registered using an `ensae.fr` email, you personal space won't be cleanup up today but will be at a later date, currently scheduled for december 31th but subject to change.

**Comment by olevitt** [comment]
Starting cleanup now. Datalab has been taken offline during the process.  
I will make sure to notify here once the cleanup is over.

**Comment by olevitt** [comment]
Cleanup is now over, Datalab has been brought back online.

Thanks for your patience and welcome back on SSPCloud :)
