### ISSUE TITLE
Authentication flow issue in Edge 95 on Windows NT 6.2

### ISSUE THREAD

**Issue by ghost** [InseeFrLab/sspcloud#3]
Hello,

There was an issue with authentication on the SSP Cloud, when trying to log in in the `datalab.sspcloud.fr`. This happened in the first part of the flow, without displaying any login page. I was able to replicate it using the browser Edge 95 on Windows NT 6.2. Had no issues using Chrome 95 on Windows NT 6.2.

Error log
```
Navegou para https://auth.lab.sspcloud.fr/auth/realms/sspcloud/protocol/openid-connect/auth?client_id=onyxia&redirect_uri=https%3A%2F%2Fdatalab.sspcloud.fr%2Fhome&state=df03a7f1-88a7-4dba-928f-a7bfbf322bb8&response_mode=query&response_type=code&scope=openid&nonce=a252c67b-e993-4729-8da7-67c9c067bf48&powerhooks_useGlobalState_isDarkModeEnabled=%5Bfalse%5D&powerhooks_useGlobalState_lastDelayedTime=%5B1635352432379%5D&powerhooks_useGlobalState_kcLanguageTag=%5B%22pt%22%5D&powerhooks_useGlobalState_isCollapsed=%5Bfalse%5D&powerhooks_useGlobalState_lng=%5B%22pt%22%5D&palette=onyxia&title=SSP%20Cloud
react-dom.production.min.js:216 

TypeError: Cannot read properties of undefined (reading 'doLogIn')
    at useKcMessage.tsx:29
    at useKcMessage.tsx:47
    at Login.tsx:200
    at sa (react-dom.production.min.js:157)
    at Va (react-dom.production.min.js:180)
    at Ua (react-dom.production.min.js:178)
    at Ba (react-dom.production.min.js:177)
    at Ys (react-dom.production.min.js:274)
    at Tc (react-dom.production.min.js:250)
    at Ec (react-dom.production.min.js:250)
        
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'doLogIn')
    at useKcMessage.tsx:29
    at useKcMessage.tsx:47
    at Login.tsx:200
    at sa (react-dom.production.min.js:157)
    at Va (react-dom.production.min.js:180)
    at Ua (react-dom.production.min.js:178)
    at Ba (react-dom.production.min.js:177)
    at Ys (react-dom.production.min.js:274)
    at Tc (react-dom.production.min.js:250)
    at Ec (react-dom.production.min.js:250)
        
Access to manifest at 'https://datalab.sspcloud.fr/favicon_package/site.webmanifest' from origin 'https://auth.lab.sspcloud.fr' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
datalab.sspcloud.fr/favicon_package/site.webmanifest:1 
        
GET https://datalab.sspcloud.fr/favicon_package/site.webmanifest net::ERR_FAILED 200
content.js:94 Content Server Web Browser Extension: not applicable for href='https://auth.lab.sspcloud.fr/auth/realms/sspcloud/protocol/openid-connect/auth?client_id=onyxia&redirect_uri=https%3A%2F%2Fdatalab.sspcloud.fr%2Fhome&state=df03a7f1-88a7-4dba-928f-a7bfbf322bb8&response_mode=query&response_type=code&scope=openid&nonce=a252c67b-e993-4729-8da7-67c9c067bf48'; 
```

Thank you in advance

**Comment by garronej** [comment]
Hi @luismferreiradeloitte,  
Thank you for reporting. This is an issue caused by [Keycloakify](https://github.com/InseeFrLab/keycloakify). I've opened it [there](https://github.com/InseeFrLab/keycloakify/issues/48)  
  
On a more general note, welcome to the project. I will be spending the day writing technical documentation to smoothen your onboarding. Maybe we could schedule a call and do a hands-on together.  

I'll keep you updated,  

Best,

**Comment by garronej** [comment]
Hi @luismferreiradeloitte,  
I can't figure out what might have appended here.  
Could you give me a hand and run:  
`console.log([].find(()=> false) === undefined)`  
![image](https://user-images.githubusercontent.com/6702424/139748732-fd04ec4a-a2ef-4fa2-b685-461c36df1464.png)

in the browser, you had this error with and tel me what it gives you.

Could you also do `navigator.language` ? 

![image](https://user-images.githubusercontent.com/6702424/139748898-d2f9b7a8-0e71-48c8-9174-2d2891052f9c.png)

Much appreciated

**Comment by ghost** [comment]
Hi @garronej ,

Thank you for your swift reply, and the documentation addition. It would be great to have a closer point of contact with you, we should schedule a call.

About the run, do you believe it's because of the navigator default language?
![image](https://user-images.githubusercontent.com/87062353/140045022-0dd5fe7a-8168-4d5c-bdac-8075172507d2.png)

Thank you

**Comment by garronej** [comment]
@luismferreiradeloitte

Português is supposed to be supported. The bug has never been reported before. I spend two hours trying to figure out what might have happened but it's still a mystery to me.  
Can you still reproduce the bug? I really would like to figure this out. Several companies relies on Keycloakify for their login, it's a big deal if it randomly break on some browser, with some language.  

> It would be great to have a closer point of contact  

Sure thing, what do you suggest? I can invite any of you on my private Discord server. Maybe you have a better suggestion?  

Best regard

**Comment by garronej** [comment]
Ok, I think I got it, the bug was in Onyxia-web and carried over to Keycloakify. Thank you for reporting!

**Comment by garronej** [comment]
@olevitt would you give me the access to close issues here plz?

**Comment by olevitt** [comment]
Done
