### ISSUE TITLE
Longue attente pour le déclenchement du CI ce jour

### ISSUE THREAD

**Issue by statnmap** [InseeFrLab/sspcloud#4]
Bonjour, 
Aujourd'hui, je dois attendre entre 10min et 1h avant que mon pipeline ne se déclenche.   
Habituellement, c'est instantané.  
Je me demande si le nombre d'utilisateur à augmenté et que nous sommes limités par la disponibilité des runners ou bien si vous avez changé quelque chose dans la configuration ?

**Comment by olevitt** [comment]
Hello, je vais regarder demain, normalement rien de nouveau niveau config. Mais si besoin on ajoutera des runners pour traiter plus de jobs en simultané

**Comment by olevitt** [comment]
Re, 
J'ai pas trouvé de trace de ralentissement (pas de conso particulièrement élévée dans le monitoring, très très peu de jobs executés ...).  
Dans le doute, je suis passé de 1 instance de runner à 5. Au moins, si yen a une qui déconne, yen aura 4 autres dispos :)
Normalement chaque instance est capable de faire 10 jobs en simultané.

Tu me tiens au courant si t'as toujours des lenteurs ?

**Comment by statnmap** [comment]
J'ai relancé des jobs aujourd'hui, mais le lancement est toujours aussi long. Entre 10 et 1h d'attente avec ce message:
![image](https://user-images.githubusercontent.com/21193866/139430113-73e2851b-a1f0-4cff-ac2d-88360446c631.png)

**Comment by olevitt** [comment]
Effectivement, j'ai le même problème. Je creuse

**Comment by olevitt** [comment]
```
WARNING: Checking for jobs... failed                runner=Fb1zfo5n status=POST https://git.lab.sspcloud.fr/api/v4/jobs/request: 409 Conflict
```

https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4360#note_199648120

on avance :)

**Comment by olevitt** [comment]
Malheureusement pour l'instant je dois conclure à un bug gitlab https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4360 ...
J'ai tenté pas mal de choses sur la dernière heure là, rien de bon :(

**Comment by olevitt** [comment]
@statnmap je t'oublie pas mais vraiment, impossible de trouver comment fixer ça pour l'instant :(

**Comment by statnmap** [comment]
Je vois ça !  
On a parfois des soucis avec Sidekiq sur notre GitLab interne. Il est trop surchargé pour traiter tous les demandes et parfois il faut stopper tout ça et relancer. Il lance tous les "jobs" GitLab qui tourne en arrière plan, mais c'est aussi lui qui gère le déclenchement du CI il me semble.  
Ça devrait être par là chez vous: https://git.lab.sspcloud.fr/admin/background_jobs  

Il y a un article GitLab qui parle de comment mieux le configurer en cas de grosse machinerie. Nous n'avons pas encore testé cela, mais ça peut aussi être une piste à explorer: https://about.gitlab.com/blog/2021/09/27/how-to-configure-sidekiq-for-gitlab-at-scale/

**Comment by olevitt** [comment]
Bien vu ! On a sidekiq en PLS, l'autoscaler a popé 10 instances (son max) et il considère quand même qu'il est en galère (alors qu'on a pas du tout le volume nécessitant 10 instances).
Bonne piste, je creuse :)

**Comment by olevitt** [comment]
Ca se confirme que ta piste était la bonne, merci :+1: 
Du coup, j'ai limité le nombre de replicas max de sidekiq à 2, j'en ai profité pour tout restart.  
Apparemment le postgres refusait les nouvelles connexions aussi, probablement parce que les 10 sidekiq qui tournaient prenaient toutes les connexions ouvertes. Ca se plaignait beaucoup des temps de réponse du redis aussi ...

Bref, je pense qu'on va tenter quelques temps avec 2 sidekiq max et voir ce que ça donne. Là les jobs trigger direct :crossed_fingers:  

Tu me dis si tu constates à nouveau des pbs ?

**Comment by statnmap** [comment]
Parfait. Merci.  
Je ré-ouvrirai cette issue si besoin. :crossed_fingers:
