### ISSUE TITLE
Shared memory des services Tensorflow

### ISSUE THREAD

**Issue by MZellou** [InseeFrLab/sspcloud#6]
Hello ! 

Lors de l'entrainement de modèles de deep learning utilisant PyTorch, la librairie utilise la shared memory afin d'effectuer la copie du dataset vers un tenseur torch. Par défaut, cette mémoire est de 64Mb, insuffisant pour profiter de la pleine puissance des GPU. En effet, cette valeur par défaut ne permet pas d'utiliser plusieurs CPU à la fois (ce qui est dommage vu le nombre dont on dispose dans les services). Cela a pour effet de ralentir grandement le temps nécessaire pour entraîner un modèle et ne permet pas de profiter de toute la puissance du GPU. 

Apparemment, il existe des solutions simples (rajouter des paramètres lors du docker run) : 
https://gitanswer.com/error-unexpected-bus-error-encountered-in-worker-this-might-be-caused-by-insufficient-shared-memory-shm-python-cloudml-samples-483222615

Est-ce que vous comprenez l'impact que ça peut avoir d'augmenter la shared memory ? Si ce n'est pas impactant, ce serait possible de l'augmenter pour qu'on puisses tester le multi-processing ?  
 
Merci !

**Comment by olevitt** [comment]
Hello :)  

A moins que je dise une connerie, l'augmentation de la shared memory c'est un truc qu'on fait déjà pour d'autres contrats dont ubuntu (on en a besoin pour des apps genre chrome). CF https://github.com/InseeFrLab/helm-charts-datascience/blob/a037c84b5f5a575d60437a271baabd5804650d12/charts/ubuntu/templates/deployment.yaml#L34  
Techniquement, ça revient à créer explicitement un volume temporaire, en mémoire, et à le monter sur /dev/shm. C'est l'équivalent du `--shm-size` de docker proposé dans ta solution.
Donc IMHO, pas de problèmes pour le faire sur les services les plus consommateurs de ce genre de trucs. Tu utilises quoi comme service du catalogue ? Le service tensorflow ?

**Comment by MZellou** [comment]
Tensorflow oui !

**Comment by olevitt** [comment]
Ça roule, j'essaie d'implémenter ça pour cette aprem

**Comment by MZellou** [comment]
Super merci ! Je pourrais tester vendredi si c'est le cas et je vous ferais un retour

**Comment by olevitt** [comment]
@MZellou : c'est fait (https://github.com/InseeFrLab/helm-charts-datascience/commit/19bbe69a26e938612c094ae0d6f44b863e6f460f). Donc dispo d'ici 5 minutes sur le sspcloud.  
Tu me diras si ça fait ce que tu veux :)

**Comment by MZellou** [comment]
C'est bon de mon côté merci beaucoup ! :+1:
