### ISSUE TITLE
Add QGIS service 

### ISSUE THREAD

**Issue by MZellou** [InseeFrLab/sspcloud#9]
Is it possible to add QGIS service to the catalog ?

**Comment by olevitt** [comment]
There appears to be an existing and maintained docker image available here : https://hub.docker.com/r/qgis/qgis/ so there is hope :)
Would you be interested and available for a work session to implement it with us ? Knowledge on what this service is about and what it's supposed to do would be really helpful for us.

**Comment by MZellou** [comment]
I use it for few months only but i'll be happy to help !

**Comment by avouacr** [comment]
There doesn't seem to be a web version of the graphical interface of QGIS, so we can't add it as a service to the catalog. So we added the Desktop version to our Ubuntu image. It seems to work fine when enough ressources (CPU & RAM) are specified at the initialisation of the service. Let us know how it goes !

**Comment by jdlom** [comment]
@avouacr I just tested the solution and it works pretty well with the ubuntu vnc service ! Thanks a lot !
